name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin

    steps:
            - name: Building ${{ matrix.TARGET }}
              run: echo "${{ matrix.TARGET }}"
        
            - uses: actions/checkout@master
            - uses: actions-rs/toolchain@v1.0.1
              with:
                toolchain: stable
                target: ${{ matrix.TARGET }}
                override: true
        
            - uses: actions-rs/cargo@v1
              with:
                use-cross: true
                command: build
                args: --verbose --release --target=${{ matrix.TARGET }}
        
            - name: Rename
              run: cp target/${{ matrix.TARGET }}/release/uptime${{ matrix.EXTENSION }} uptime-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        
            - uses: actions/upload-artifact@master
              with:
                name: uptime-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
                path: uptime-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        
            - uses: svenstaro/upload-release-action@v2
              name: Upload binaries to release
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: uptime-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
                asset_name: uptime-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
                tag: ${{ github.ref }}
                prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
                overwrite: true